#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e

base_path=`pwd`
#source_file_path=`echo ${base_path%bigtop*}`
#replace_file_path="${source_file_path}SubstitutionFiles/hbase.sh"
#tar_output_folder="${source_file_path}hdp-output"
#source_file_path=${source_file_path}HDP_COMPONENT_VARIABLES.sh
#source ${source_file_path}
#. `dirname $0`/bigtop.bom

# Getting the old version of Hbase from pom.xml.
old_hbase_version=`$MAVEN_HOME/bin/mvn -B org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v Downloading | grep -v Downloaded | grep -v '\['`

echo "Old hbase version captured from maven command = $old_hbase_version"

if [[ -z "${old_hbase_version}" ]]; then
   echo "Maven command return null hence defining a fixed version."
   old_hbase_version="0.96.0"
else
   echo "Maven command successfully returned the hbase version"
   echo "Old hbase version captured from maven command ====>  $old_hbase_version" 
fi
echo;echo
set -x
bash dev-support/generate-hadoopX-poms.sh ${old_hbase_version} ${hbase_jar_version}
set +x
echo;echo
# modifying the properties prior to build
#source ${replace_file_path}
echo "======== Hbase Build for tarball..... ======="

echo;echo
echo "======cleaning the maven build ===="
set -x
MAVEN_OPTS="-Xmx3g" $MAVEN_HOME/bin/mvn clean
set +x
echo;echo
echo "====== Running actual build with hadoop-2 profile for hbase  ===="

set -x
BUILD_HBASE_HADOOP2_OPTS=-DskipTests
MAVEN_OPTS="-Xmx3g" $MAVEN_HOME/bin/mvn -f pom.xml.hadoop2 ${BUILD_HBASE_HADOOP2_OPTS} \
    		package assembly:single "$@"
set +x

rm -rf build
mkdir build
find . -name ${hbase_name}-${hbase_jar_version}-bin.tar.gz
tar -C build --strip-components=1 -xzf hbase-assembly/target/${hbase_name}-${hbase_jar_version}-bin.tar.gz

