# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    manager_ram = 1024
    node_ram = 1024
    node_count = 2

    config.vm.box = "buildoop-cluster"
    config.vm.box_url = "http://asterix.cloud.cediant.es/buildoop/boxes/buildoop-centos.box"

    # Hadoop Manager
    config.vm.define "manager" do |manager_config|
        manager_config.vm.hostname = "hadoop-manager.buildoop.org"
        manager_config.vm.network :forwarded_port, guest: 7180, host: 7180
        manager_config.vm.network :private_network, ip: "192.168.33.11"
        manager_config.vm.provider :virtualbox do |vb|
            vb.gui = false
            vb.customize ["modifyvm", :id, "--ioapic", "on"]
            vb.customize ["modifyvm", :id, "--memory", "#{manager_ram}"]
            vb.customize ["modifyvm", :id, "--cpus", 2]
        manager_config.vm.provision :puppet do |puppet|
            puppet.manifests_path = "../../cm/manifests"
            puppet.manifest_file  = "default.pp"
        end
      end
    end

     # Create Datanodes
     node_count.times do |i|
     id = i+1
     config.vm.define "node#{id}" do |node_config|
         node_config.vm.hostname = "hadoop-node#{id}"
      	 node_config.vm.network :private_network, ip: "192.168.33.1#{id+1}"
      	 node_config.vm.provider :virtualbox do |vb|
             vb.customize ["modifyvm", :id, "--memory", "#{node_ram}"]
      end
    end
  end 

end
