#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -xv

base_path=`pwd`
source_file_path=`echo ${base_path}`
tar_output_folder="${source_file_path}"
#source_file_path=${source_file_path}HDP_COMPONENT_VARIABLES.sh
#source ${source_file_path}
hadoop_jar_version="2.2.0"

#if [ -z "$BUNDLE_SNAPPY" ] ; then
#  [ -f /usr/lib/libsnappy.so ] && BUNDLE_SNAPPY="-Dsnappy.prefix=x -Dbundle.snappy=true -Dsnappy.lib=/usr/lib"
#  [ -f /usr/lib64/libsnappy.so ] && BUNDLE_SNAPPY="-Dsnappy.prefix=x -Dbundle.snappy=true -Dsnappy.lib=/usr/lib64"
#fi

mkdir -p build/src
mkdir -p ${tar_output_folder}

#DEPLOY_OPTS="-DdistMgmtStagingId=${repo_id} -DdistMgmtStagingUrl=${nexus_repo_url}"
MAVEN_PROFILES="-Pdist -Pnative -Psrc -Dtar"
# Build artifacts
MAVEN_SKIP_TESTS="-DskipTests -DskipITs"
$MAVEN_HOME/bin/mvn versions:set -DnewVersion=${hadoop_jar_version} ${MAVEN_PROFILES} ${MAVEN_SKIP_TESTS} install
#$MAVEN_HOME/bin/mvn $BUNDLE_SNAPPY ${MAVEN_PROFILES} ${DEPLOY_OPTS} ${MAVEN_SKIP_TESTS} deploy "$@"
#$MAVEN_HOME/bin/mvn ${HADOOP_DEPLOY_OPTS} deploy "$@"
#$MAVEN_HOME/bin/mvn ${HADOOP_DEPLOY_OPTS} site site:stage $@

(cd build ; tar --strip-components=1 -xzf  ../hadoop-dist/target/hadoop-${hadoop_jar_version}.tar.gz)
(cd build/src ; tar --strip-components=1 -xzf  ../../hadoop-dist/target/hadoop-${hadoop_jar_version}-src.tar.gz)

# Copy generated docs
mkdir -p build/share

# Create a manifest for hadoop client package
(cd hadoop-client/target/hadoop-client-*/share/hadoop/client/lib ; ls) > build/hadoop-client.list

# Copy fuse output to the build directory
cp hadoop-hdfs-project/hadoop-hdfs/target/native/main/native/fuse-dfs/fuse_dfs build/bin/

mkdir ${tar_output_folder}/source_tar/
#Copying the Hadoop binary tarball to the output folder
cp ${base_path}/hadoop-dist/target/hadoop-${hadoop_jar_version}.tar.gz ${tar_output_folder}/
cp ${base_path}/hadoop-dist/target/hadoop-${hadoop_jar_version}-src.tar.gz ${tar_output_folder}/source_tar/

#md5sum ${base_path}/hadoop-dist/target/hadoop-${hadoop_jar_version}*.tar.gz
#md5sum ${tar_output_folder}/*${hadoop_name}* 
#md5sum ${tar_output_folder}/source_tar/*${hadoop_name}*




