#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex 

echo "[TRACE] Maven CLEAN INSTALL"
mvn -f maven/pom.xml clean install "$@"

# Hack when the source is downloaded from git
chmod +x desktop/core/ext-py/markdown/bin/markdown

# Hack for custom version
#sed -i -r "s/VERSION=.*/VERSION=\"3.5.0.cdh5.0.0\"/" VERSION

echo "[TRACE] make apps docs"
make apps docs

# Workaround for https://issues.cloudera.org/browse/HUE-1603 
rename .md .html docs/user-guide/*.md || :

echo "[TRACE] relocatable"
# Make the entire tree relocatable
bash -xv tools/relocatable.sh

echo "[TRACE] make prod"
# Make the entire tree relocatable
make prod

