#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if [ "x$SCALA_HOME" = "x" ]; then
    echo "SCALA_HOME has to be set before the build can run"
    exit 2
fi

HADOOP_VERSION=2.2.0

BUILD_OPTS="-Pyarn -Dhadoop.version=2.2.0 \
	    -Dyarn.version=2.2.0 \
	    -Dprotobuf.version=2.5.0 \
	    -DskipTests"

# -Dhbase.version=???

export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m \
		   -XX:PermSize=1024m -XX:MaxPermSize=1024m"

# bigtop-dist profile is hardcoded in the original source code.
mvn -Phadoop-provided $BUILD_OPTS clean package




