#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

echo SBT_OPTS="-Xmx512M -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M -Divy.home=${HOME}/.ivy2 -Dsbt.ivy.home=${HOME}/.ivy2 -Dsbt.boot.directory=${HOME}/.sbt/boot/ -Duser.home=${HOME} -Drepo.maven.org=$IVY_MIRROR_PROP -Dreactor.repo=file://${HOME}/.m2/repository" > ${HOME}/.sbtconfig

java -Xmx512M \
	-XX:+CMSClassUnloadingEnabled \
	-XX:PermSize=256M \
	-XX:MaxPermSize=512M \
	-Divy.home=${HOME}/.ivy2 \
	-Dsbt.ivy.home=${HOME}/.ivy2 \
	-Dsbt.boot.directory=${HOME}/.sbt/boot/ \
	-Duser.home=${HOME} \
	-Drepo.maven.org=$IVY_MIRROR_PROP \
	-Dreactor.repo=file://${HOME}/.m2/repository \
	-Dbuild.number="$BUILD_NUMBER" \
	-jar ./lib/sbt-launch.jar "++2.9.2 package"

java -XX:+CMSClassUnloadingEnabled \
	-XX:PermSize=256M \
	-XX:MaxPermSize=512M \
	-Divy.home=${HOME}/.ivy2 \
	-Dsbt.ivy.home=${HOME}/.ivy2 \
	-Dsbt.boot.directory=${HOME}/.sbt/boot/ \
	-Duser.home=${HOME} \
	-Drepo.maven.org=$IVY_MIRROR_PROP \
	-Dreactor.repo=file://${HOME}/.m2/repository \
	-Dbuild.number="$BUILD_NUMBER" \
	-jar ./lib/sbt-launch.jar "++2.9.2 assembly-package-dependency"

