#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -xv

storm_version="apache-storm-0.9.2-incubating"
JAVA_OPTS=""
MAVEN_OPTS="-DskipTests -Dgpg.skip"

mvn clean package $MAVEN_OPTS
pushd storm-dist/binary/
mvn package $MAVEN_OPTS
popd
mkdir build
#tar --strip-components=1 -xzf storm-dist/binary/target/${storm_version}.tar.gz -C build
tar -xzf storm-dist/binary/target/${storm_version}.tar.gz -C build
mv build/${storm_version}/* build

